name: CD pipeline

on:
  workflow_run:
    workflows: CI build pipeline
    branches: [master,develop]
    types: [completed]
  workflow_dispatch:

jobs:
  Deploy:
    runs-on: VM1
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4.1.3
        with:
          name: artifact
          workflow: CI build pipeline
          path: build_artifacts
          
      - name: Deploy_to_test_path
        run: |
          copy ./build_artifacts C:/TestPath
  
    
