name: CD pipeline

on:
  workflow_run:
    workflows: CI build pipeline
    branches: [master,develop]
    types: [completed]
  workflow_dispatch:

jobs:
  Deploy:
    runs-on: VM1
    steps:
      - name: Download build artifact
        uses: dawidd6/action-download-artifact@v3
        with:
          name: artifact
          workflow: CI Build Pipeline.yml
          path: build_artifacts
          
      - name: Deploy_to_test_path
        run: |
          xcopy /s /y ./build_artifacts/* C:/TestPath
  
    
